baseURL = 'https://about.silicon.moe/'
languageCode = 'en-us'
title = 'About SiliconForest'
theme = 'risotto'

enableRobotsTXT = true

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "About SiliconForest"
description = "About SiliconForest"
#logo = "images/siflogo-light.svg"

[menu]
[[menu.main]]
  identifier = "notice"
  name = "Notice"
  url = "/notice/"
  weight = 10
